!classDefinition: #AdeleGoldberg category: #Forms1-2-3!
DenotativeObject subclass: #AdeleGoldberg
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Forms1-2-3'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'AdeleGoldberg class' category: #Forms1-2-3!
AdeleGoldberg class
	instanceVariableNames: ''!

!AdeleGoldberg class methodsFor: '-- all --' stamp: 'mg 3/13/2024 15:34:48'!
fechaDeNacimiento
	^July/22/1945! !


!classDefinition: #AlanKay category: #Forms1-2-3!
DenotativeObject subclass: #AlanKay
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Forms1-2-3'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'AlanKay class' category: #Forms1-2-3!
AlanKay class
	instanceVariableNames: ''!

!AlanKay class methodsFor: '-- all --' stamp: 'mg 3/13/2024 15:33:37'!
fechaDeNacimiento
	^May/17/1940! !


!classDefinition: #AlanTuring category: #Forms1-2-3!
DenotativeObject subclass: #AlanTuring
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Forms1-2-3'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'AlanTuring class' category: #Forms1-2-3!
AlanTuring class
	instanceVariableNames: ''!

!AlanTuring class methodsFor: 'info personal' stamp: 'mg 3/13/2024 15:27:14'!
fechaDeNacimiento
	^June/23/1912! !


!classDefinition: #JohnVonNeumann category: #Forms1-2-3!
DenotativeObject subclass: #JohnVonNeumann
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Forms1-2-3'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'JohnVonNeumann class' category: #Forms1-2-3!
JohnVonNeumann class
	instanceVariableNames: ''!

!JohnVonNeumann class methodsFor: '-- all --' stamp: 'mg 3/13/2024 15:30:52'!
fechaDeNacimiento
	^December/28/1903! !
